
const images = {
  'abstract':{
    152:{title:'Aeroplane Flying', year:1915, painter:'Kazimir Malevich'},
    153:{title:'A man in a cafe', year:1914, painter:'Juan Gris'},
    154:{title:"Poème d'amour", year:1962, painter:'Hans Hofmann'},
    155:{title:'Senecio', year:1922, painter:'Paul Klee'},
    156:{title:'The Joy of Life', year:1930, painter:'Robert Delaunay'},
    157:{title:'Tree', year:1935, painter:'Arthur Dove'},
    158:{title:'Two Young Girls', year:1971, painter:'Karel Appel'},
    159:{title:'Untitled #2', year:1986, painter:'Willem de Kooning'},
    160:{title:'Circles in a Circle', year:1923, painter:'Wassily Kandinsky'},
    161:{title:'Femme dans la nuit ', year:1967, painter:'Joan Miro'},
  },
  'portrait':{
    346:{title:'Portrait of an Old Woman', year:1612, painter:'Guido Reni'},
    347:{title:'omakuva', year:1895, painter:'Helene Schjerfbeck'},
    348:{title:'Portrait of Maude Abrantes', year:1907, painter:'Amedeo Modigliani'},
    349:{title:'Portrait of a young North-African woman', year:1874, painter:'Jean-François Portaels'},
    350:{title:'Portrait of Ayuba Suleiman Diallo', year:1739, painter:'William Hoare'},
    351:{title:"Portrait de l'actrice Jeanne Samary", year:1877, painter:'Pierre-Auguste Renoir'},
    352:{title:'Portrait of a Peasant', year:1888, painter:'Vincent van Gogh'},
    353:{title:'Portrait of an Unknown Woman', year:1883, painter:'Ivan Kramskoi'},
    354:{title:'Portrait of an African Slave Woman', year:1580, painter:'Annibale Carracci'},
    355:{title:'Child in a Straw Hat', year:1886, painter:'Mary Cassatt'},
    356:{title:'Peter I on his deathbed', year:1725, painter:'Ivan Nikitin'},
    357:{title:'Portrait of a child of the House of Redetti', year:1570 , painter:'Giovan Battista Moroni'},
    359:{title:'Head of a young girl in a bonnet', year:1764, painter:'Jean-Baptiste Greuze'},
    360:{title:'Peasant Girl', year:1919, painter:'István Nagy'},
    361:{title:'Peasant Woman with Green Headscarf', year:1879, painter:'Ion Andreescu'},
    362:{title:'Portrait of Ivan Fyodorovich Radov', year:1877, painter:'Ilya Repin'},
    363:{title:'The Belle of the Alley', year:1913, painter:'George W Lambert'},
    364:{title:'The Green Line', year:1905, painter:'Henri Matisse'},
    365:{title:'Portrait of a peasant', year:1899, painter:'Vasily Vereshchagin'},
    366:{title:'Portrait of an elderly woman', year:1832, painter:'Wilhelm Bendz'},
    367:{title:'Portrait of peasant girl', year:1892, painter:'Jan Zasiedatel'},
    368:{title:'Lycinna', year:1918, painter:'John William Godward'},
  },
  'landscape':{
    723:{title:'Mountain landscape', year:1831, painter:'Wilhelm Bendz'},
    724:{title:'Riders in Canyon de Chelly', year:1922, painter:'Edgar Payne'},
    725:{title:'Lavender Hills', year:1918, painter:'Edgar Payne'},
    726:{title:'Landscape with Herd of Buffalo on the Upper Missouri', year:1833, painter:'Karl Bodmer'},
    727:{title:'Mast-Timber forest in Viatka Province', year:1872, painter:'Ivan Shishkin'},
    728:{title:'The Matterhorn', year:1867, painter:'Albert Bierstadt'},
    729:{title:'Storm in the Mountains', year:1870, painter:'Albert Bierstadt'},
    730:{title:'Kings River Canyon California', year:1870, painter:'Albert Bierstadt'},
    731:{title:'At Templestowe', year:1889, painter:'Arthur Streeton'},
    732:{title:'Winter Sun in Hafnarfjörður', year:1930, painter:'Asgrimur Jonsson'},
    733:{title:'The Kern River Valley', year:1871, painter:'Albert Bierstadt'},
    734:{title:'On the Saco', year:1871, painter:'Albert Bierstadt'},
    735:{title:'Autumn Landscape', year:1891, painter:'Charles Ethan Porter'},
    736:{title:'Mount Aetna from Taormina', year:1843, painter:'Thomas Cole'},
    737:{title:'Emigrants Crossing the Plains', year:1869, painter:'Albert Bierstadt'},
    738:{title:'Sunset Over New York Bay', year:1873, painter:'Sanford Robinson Gifford'},
    739:{title:'In the Wilderness Twilight', year:1860, painter:'Sanford Robinson Gifford'},
    740:{title:'Rye', year:1878, painter:'Ivan Shishkin'},
    741:{title:'Study of Cotopaxi', year:1861, painter:'Frederic Edwin Church'},
    742:{title:'The Wreck', year:1852, painter:'Frederic Edwin Church'},
    743:{title:'The Falls of St. Anthony', year:1884, painter:'Albert Bierstadt'},
    744:{title:'Western Kansas', year:1979, painter:'Albert Bierstadt'},
    745:{title:'Canyon de Chelly', year:1917, painter:'Edgar Payne'},
    746:{title:'Hafnarfjörður Town', year:1930, painter:'Asgrimur Jonsson'},
    747:{title:'Soleienatt', year:1915, painter:'Nikolai Astrup'},
    748:{title:'On the New Jersey Shore', year:1897, painter:'William Trost Richards'},
  },
  'impressionism':{
    575:{title:'In the afternoon', year:1891, painter:'John Peter Russell'},
    576:{title:'Le corsage rouge', year:1885, painter:'Berthe Morisot'},
    577:{title:'In the Woods', year:1880 , painter:'Pierre-Auguste Renoir'},
    578:{title:'The Studio Boat', year:1874, painter:'Claude Monet'},
    579:{title:'Wheat Field', year:1873, painter:'Alfred Sisley'},
    580:{title:'Niña en la playa', year:1910, painter:'Joaquin Sorolla y Bastida'},
    581:{title:'Church at Old Lyme', year:1903, painter:'Childe Hassam'},
    582:{title:'Flores', year:1917, painter:'Eliseu Visconti'},
    583:{title:'Houses of Parliament', year:1904, painter:'Claude Monet'},
    584:{title:'Nächtliches Paris', year:1927, painter:'Konstantin Korovin'},
    585:{title:'Rough sea', year:1900, painter:'John Peter Russell'},
    586:{title:'Rafales de vent', year:1911, painter:'Armand Guillaumin'},
    587:{title:'Sunset at Ivry', year:1873, painter:'Armand Guillaumin'},
  }
}

